name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: SendEmail
          runtime: go113
          region: us-east4

      - name: Display URL
        run: echo GCP function deployed to "${{ steps.deploy.outputs.url }}"